### ISSUE TITLE
Bostrom Meta Issue

### ISSUE THREAD

**Issue by litvintech** [cybercongress/go-cyber#590]
[ ] Migration to Stargate
[ ] Inter Knowledge Protocol over IBC (query rank value, interchain cyberlink)
[ ] Fee/Bandwidth system for resources (Amper's bandwidth for cyberlink ops, other ops fee)
[ ] Integration of new system resources (Volts + Ampers)
[ ] Energy module implementation (Routing of V&A)
[ ] Resource module implementation (Resource Processing Units over VM)
[ ] Cron module implementation (with medium execution guarantees)
[ ] Rich system of CosmWasm's Query/Tx bindings to modules
[ ] Entropy/Luminosity/Karma implementation
[ ] Backlinks API
[ ] Group module merge
[ ] Authz module merge
[ ] FeeGrant module merge
[ ] Storage-level support (cyberlinks/particles) for future pruning strategies
[ ] Debug tools (storage/graph)
[ ] Graph export for side analytics tools
[ ] Rich telemetry system
[ ] Tests

**Comment by litvintech** [comment]
Current implementation progress is around 65%

**Comment by cyb-master** [comment]
- [ ] Prepare and verify Genesis of Bostrom and Cyber
- [ ] Economics simulation
- [ ] Release new [protocol spec](https://github.com/cybercongress/cyber/pull/47)
- [ ] Switch from cids to hashes
- [ ] Bostrom counter
- [ ] Fix usability of cyber.page
- [ ] Release go-cyber
- [ ] Move cyber.page to cyb.ai
